// Intrinsic dimensions for everything in public/, generated by
// `npm run assets` (see scripts/generate-assets.mjs). The media components use
// these to reserve a correctly-shaped box — and show a skeleton in it — while
// the real file is still downloading, so revealing a message never shifts the
// layout underneath it.
import assets from "../data/assets.json";

export interface AssetMeta {
  width: number;
  height: number;
  aspectRatio: number;
}

const images: Record<string, AssetMeta> = assets.images;

/**
 * Every video on the site is a YouTube or Vimeo embed, so there's no file to
 * measure — they're all 16:9 and the player stretches to fill whatever box it
 * is given.
 */
export const VIDEO_ASSET: AssetMeta = assets.defaults.video;

/**
 * Looks up an image by the path the app references it with ("/images/foo.png").
 * Returns undefined for anything not in public/ (a remote URL, say) or for a
 * file added since the last `npm run assets` run — callers fall back to
 * rendering without a reserved box rather than guessing at a shape.
 */
export const getImageMeta = (src: string | undefined): AssetMeta | undefined => {
  if (!src) return undefined;
  const path = src.split(/[?#]/)[0];
  return images[path] ?? images[decodeURIComponent(path)];
};
