// Intrinsic dimensions for everything in public/, generated by
// `npm run assets` (see scripts/generate-assets.mjs). The media components use
// these to reserve a correctly-shaped box — and show a skeleton in it — while
// the real file is still downloading, so revealing a message never shifts the
// layout underneath it.
import assets from "../data/assets.json";

export interface AssetMeta {
  width: number;
  height: number;
  aspectRatio: number;
}

const images: Record<string, AssetMeta> = assets.images;
const videos: Record<string, AssetMeta> = assets.videos;

/**
 * Fallback shape for YouTube/Vimeo embeds: there's no file to measure, they're
 * all 16:9, and the player stretches to fill whatever box it is given. Videos
 * served out of public/ are measured — see getVideoMeta.
 */
export const VIDEO_ASSET: AssetMeta = assets.defaults.video;

/**
 * Looks up a self-hosted video by its public path ("/videos/foo.mp4").
 * Returns undefined for embeds (a YouTube/Vimeo URL) and for files added since
 * the last `npm run assets` run — callers fall back to VIDEO_ASSET's 16:9.
 */
export const getVideoMeta = (src: string | undefined): AssetMeta | undefined => {
  if (!src) return undefined;
  const path = src.split(/[?#]/)[0];
  return videos[path] ?? videos[decodeURIComponent(path)];
};

/**
 * Looks up an image by the path the app references it with ("/images/foo.png").
 * Returns undefined for anything not in public/ (a remote URL, say) or for a
 * file added since the last `npm run assets` run — callers fall back to
 * rendering without a reserved box rather than guessing at a shape.
 */
export const getImageMeta = (src: string | undefined): AssetMeta | undefined => {
  if (!src) return undefined;
  const path = src.split(/[?#]/)[0];
  return images[path] ?? images[decodeURIComponent(path)];
};
